"""Shared resources for repo scripts."""

import json
from pathlib import Path

BASE_DIR = Path(__file__).parents[1]
DOCS_DIR = BASE_DIR / "docs"


def generated_notice(script_name: str) -> str:
    return f"<!-- Auto-generated by scripts/{script_name}. Do not edit. -->"


def schema_type_str(schema: dict) -> str:
    """Render a property schema's type as a compact human-readable string."""
    if "const" in schema:
        return f"const `{json.dumps(schema['const'])}`"
    if "enum" in schema:
        return "enum"
    if "anyOf" in schema:
        return " | ".join(
            schema_type_str(option) for option in schema["anyOf"]
        )
    if "oneOf" in schema:
        return " | ".join(
            schema_type_str(option) for option in schema["oneOf"]
        )
    type_ = schema.get("type")
    if type_ == "array":
        items = schema.get("items")
        if isinstance(items, dict):
            return f"array of {schema_type_str(items)}"
        return "array"
    if isinstance(type_, list):
        return " | ".join(type_)
    if type_ is None:
        return "any"
    if "format" in schema:
        return f"{type_} ({schema['format']})"
    return type_


def property_constraints(schema: dict) -> list[str]:
    """Collect constraint notes (bounds, defaults, enums) for a property."""
    notes = []
    for key, label in [
        ("default", "default"),
        ("minimum", "minimum"),
        ("maximum", "maximum"),
        ("exclusiveMinimum", "exclusive minimum"),
        ("exclusiveMaximum", "exclusive maximum"),
        ("minLength", "min length"),
        ("maxLength", "max length"),
        ("minItems", "min items"),
        ("maxItems", "max items"),
        ("pattern", "pattern"),
    ]:
        if key in schema and schema[key] is not None:
            notes.append(f"{label}: `{json.dumps(schema[key])}`")
    if "enum" in schema:
        values = ", ".join(f"`{json.dumps(v)}`" for v in schema["enum"])
        notes.append(f"one of: {values}")
    return notes
